"""add indexes and fix room backref

Revision ID: ba5838b4c6c9
Revises: 6fd2ef10a3c2
Create Date: 2026-04-21 15:09:05.880376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba5838b4c6c9'
down_revision = '6fd2ef10a3c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_index('ix_course_lecturer', ['lecturer_id'], unique=False)
        batch_op.create_index('ix_course_programme', ['programme_id'], unique=False)

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.create_index('ix_enrollment_course', ['course_id'], unique=False)
        batch_op.create_index('ix_enrollment_student', ['student_id'], unique=False)

    with op.batch_alter_table('lecture', schema=None) as batch_op:
        batch_op.create_index('ix_lecture_course', ['course_id'], unique=False)
        batch_op.create_index('ix_lecture_day_time', ['day', 'start_time', 'end_time'], unique=False)
        batch_op.create_index('ix_lecture_lecturer', ['lecturer_id'], unique=False)

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index('ix_notif_lecture', ['lecture_id'], unique=False)
        batch_op.create_index('ix_notif_user_read', ['user_id', 'is_read'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_email', ['email'], unique=True)
        batch_op.create_index('ix_user_role', ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_role')
        batch_op.drop_index('ix_user_email')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index('ix_notif_user_read')
        batch_op.drop_index('ix_notif_lecture')

    with op.batch_alter_table('lecture', schema=None) as batch_op:
        batch_op.drop_index('ix_lecture_lecturer')
        batch_op.drop_index('ix_lecture_day_time')
        batch_op.drop_index('ix_lecture_course')

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.drop_index('ix_enrollment_student')
        batch_op.drop_index('ix_enrollment_course')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_index('ix_course_programme')
        batch_op.drop_index('ix_course_lecturer')

    # ### end Alembic commands ###
