"""add class_message and online_link to lecturer

Revision ID: f74fba6c1ddc
Revises: ba5838b4c6c9
Create Date: 2026-04-26 19:19:33.974871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f74fba6c1ddc'
down_revision = 'ba5838b4c6c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lecture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('online_link', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lecture', schema=None) as batch_op:
        batch_op.drop_column('online_link')
        batch_op.drop_column('class_message')

    # ### end Alembic commands ###
